wandb: Currently logged in as: kataoka0511 (junkataoka). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.7 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.3
wandb: Run data is saved locally in /data/home/jkataok1/DA_DFD/wandb/run-20230726_222907-1dj1505y
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run log/CWRU0toIMS0_lr0.005_e200_b128
wandb: ‚≠êÔ∏è View project at https://wandb.ai/junkataoka/DA_DFD
wandb: üöÄ View run at https://wandb.ai/junkataoka/DA_DFD/runs/1dj1505y
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: üöÄ View run log/CWRU0toIMS0_lr0.005_e200_b128 at: https://wandb.ai/junkataoka/DA_DFD/runs/1dj1505y
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230726_222907-1dj1505y/logs
Traceback (most recent call last):
  File "src/main.py", line 152, in <module>
    main(args)
  File "src/main.py", line 126, in main
    val_dict = validate(model, src_val_dataloader, tar_val_dataloader, args.num_classes)
  File "/data/home/jkataok1/DA_DFD/src/validation.py", line 19, in validate
    src_cls = model(src_input)
  File "/data/home/jkataok1/mlenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/jkataok1/mlenv/lib/python3.7/site-packages/torch/autocast_mode.py", line 198, in decorate_autocast
    return func(*args, **kwargs)
  File "/data/home/jkataok1/DA_DFD/src/ast_models.py", line 175, in forward
    x = self.v.patch_embed(x)
  File "/data/home/jkataok1/mlenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/jkataok1/DA_DFD/src/ast_models.py", line 32, in forward
    x = self.proj(x).flatten(2).transpose(1, 2)
  File "/data/home/jkataok1/mlenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/jkataok1/mlenv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/home/jkataok1/mlenv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (2048 x 1). Kernel size: (16 x 16). Kernel size can't be greater than actual input size
srun: error: compute130: task 0: Exited with exit code 1
